name: 'webofmars-nfs'
maintainer: 'webofmars <contact@webofmars.com>'
description: |
  Internal NFS used by webofmars
defaultVersion: 'v1.1.1'
url: https://github.com/webofmars/meero-catalog
category: 'Storage'
