name: 'webofmars-nfs'
maintainer: 'Frederic Leger <contact@webofmars.com>'
description: |
  Internal NFS used by webofmars
defaultVersion: v1.1.2
url: https://github.com/webofmars/meero-catalog
category: 'Storage'
