version: '2'
catalog:
  name: "debug-nfs"
  version: 1
  description: |
    Stack to debug rancher-nfs setup
    You will need to prepare your env with a 'rancher volumes create --driver rancher-nfs test-nfs'
  # minimum_rancher_version:
  # maximum_rancher_version:
  # upgrade_from: # The previous versions that this template can be upgraded from
  questions:

services:
  nfs-test-1:
    start_on_create: true
