version: '2'

.catalog:
  name: "gitlab-multi-runner"
  version: "v1.0.0"
  description: "a Gitlab pipelines multi-runner, that will spawn privates runners in your infra."
  questions:
    - variable: "GITLAB_URL"
      label: "Gitlab Url"
      description: "Url to your Gitlab CI endpoint"
      type: "string"
      default: "https://gitlab.com/ci"
      required: true

    - variable: "GITLAB_TOKEN"
      label: "Gitlab Token"
      description: "Token provided in you project settings"
      type: "string"
      default: "xxxxxxxxxxxxxxxxxxxx"
      required: true

services:
  gitlab-runner-config:
    scale: 1
    start_on_create: true
  gitlab-runner:
    start_on_create: true