name: 'Bleemeo'
maintainer: 'Frederic Leger <contact@webofmars.com>'
description: |
  a bleemeo monitoring stack, check https://www.bleemeo.com for pricing and free plans
  brought to you by webofmars OSS program
category: 'Monitoring'
url: 'https://github.com/webofmars/meero-catalog'
defaultVersion: v0.1.2
labels:
  io.rancher.orchestration.supported: 'cattle,mesos,swarm,kubernetes'