name: webofmars-ntpd
description: |
  A basic ntpd server as containers. Used to keep your rancher nodes synchronized in time
  which is very important for accounting, logs & ssl services.
  Brought to you by webofmars (www.webofmars.com) OSS programm
version: v1.0.0
category: Infrastructure
