name: 'jenkins-phpci'
maintainer: 'Frederic Leger <contact@webofmars.com>'
description: |
  webofmars Jenkins PHPCI who is docker / rancher / aws aware.
defaultVersion: v1.0.5
url: https://github.com/webofmars/meero-catalog
category: 'Continuous Integration'