.catalog:
  name: jenkins-phpci
  version: 1
  description: |
    Jenkins container with PHP CI & cloud in mind :
    - aws support
    - docker support
    - rancher support

jenkins-phpci-primary:
  scale: 1

jenkins-phpci-loadbalancer:
  load_balancer_config:
    haproxy_config: {}
  health_check:
    port: 42
    interval: 2000
    unhealthy_threshold: 3
    healthy_threshold: 2
    response_timeout: 2000