version: '2'

.catalog:
  name: webofmars-nfs
  version: 1.1.1
  description: |

nfsserver:
  start_on_create: true

nfs-driver:
  storage_driver:
    name: rancher-nfs
    scope: environment
    volumeAccessMode: multiHostRW
  start_on_create: true
