name: 'debug-nfs'
maintainer: 'Frederic Leger <contact@webofmars.com>'
description: |
  Simple rancher-nfs debug stack
category: 'Infrastructure'
url: https://github.com/webofmars/meero-catalog
defaultVersion: 'v1.0.0'